### ISSUE TITLE
Support Android?

### ISSUE THREAD

**Issue by TIAOPINGZHONGGUO** [LTVA1/klystrack#2]
Dear developer, I like your software very much. Will this software be updated continuously and support Android devices in the future? I like his voice and his retro style very much!😍😍🤩👍👍👍

**Comment by LTVA1** [comment]
I plan to make a special app for tunes playback, but it would be difficult to use the tracker on Android with current UI. Also I don't have any experience with porting apps on Android.

**Comment by LTVA1** [comment]
So the answer is: probably yes but in distant future for `.kt` files playback (and even with all planned optimizations real-time synthesis is a heavy task for average smartphone so I would include `.wav`/`.flac` renderer so user would be able to render the song to audio file if they find that their phone is too slow to properly play the song), most probably no for the tracker (song editor) itself.
